#!/usr/bin/env bash
# How to Use:
# ./1-world_wide_web <domain> <subdomain>
# This script will show  info. about fomains and subdomains.

# Define a func that queries the domains using 'dig'
show_domain_metadata () {
    query=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $query" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" -eq 1 ]
then
  show_domain_metadata "$1" "www"
  show_domain_metadata "$1" "lb-01"
  show_domain_metadata "$1" "web-01"
  show_domain_metadata "$1" "web-02"
elif [ "$#" -eq 2 ]
then
  show_domain_metadata "$1" "$2"
fi
