#!/usr/bin/env bash
# Transfers one specified file to a remote server.
# Takes 4 positional args:
#  First: path to file to send
#  Second: remote server IP address
#  Third: the username to connect with through scp.
#  Four: path to the ssh private key scp uses for handshake.

if [ $# -lt 4 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
