#!/usr/bin/env bash
# This script makes a web server to run as nginx user instead of the default root user.
sed -i "s|#user www-data|user nginx|" /etc/nginx/nginx.conf
sed -i "s/80/8080/" /etc/nginx/sites-available/default
chmod u+rw /etc/nginx/nginx.conf
chmod go-w /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
